name: ikms
description: Schedule of classes

publish_to: "none"

version: 1.1.8+19

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  get: ^4.6.6
  intl: ^0.18.1
  swipe: ^0.0.1
  isar: ^3.1.0+1
  shimmer: ^3.0.0
  ficonsax: ^0.0.3
  timezone: ^0.9.2
  google_fonts: ^6.1.0
  grouped_list: ^5.1.2
  url_launcher: ^6.2.4
  bottom_picker: ^2.3.3
  path_provider: ^2.1.2
  dynamic_color: ^1.6.9
  table_calendar: ^3.0.9
  dio_smart_retry: ^6.0.0
  yandex_mobileads: ^6.2.0
  flutter_timezone: ^1.0.8
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  isar_flutter_libs: ^3.1.0+1
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^16.3.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  dependency_validator: ^3.2.3
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
